# Generated by Django 5.1 on 2025-03-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_photo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='category',
            field=models.CharField(choices=[('landscape', 'Landscape'), ('portrait', 'Portrait'), ('animal', 'Animal')], default='landscape', max_length=20),
        ),
    ]
