# Generated by Django 5.1 on 2025-03-20 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_photo_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='description',
        ),
    ]
