# Generated by Django 5.1 on 2025-04-16 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_photo_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='category',
            field=models.CharField(choices=[('coverphoto', 'Cover Photo'), ('landscape', 'Landscape'), ('portrait', 'Portrait'), ('animal', 'Animal')], default='landscape', max_length=20),
        ),
    ]
